version: 3.0
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
  redis:
    image: redis:5.0
    container_name: redis
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"
  rabbitmq:
    container_name: mq
    image: rabbitmq:3.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
networks:
  default:
    driver: bridge
    name: local_host