version: "3"
services:
  seata-server:
    image: seataio/seata-server:latest
    container_name: seata-server
    ports:
      - 8091:8091
    environment:
      - SEATA_PORT=8091
      - SEATA_IP=192.168.2.80
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
    volumes:
      - ./config:/root/seata-config
networks:
  default:
    driver: bridge
    name: local_host